name: CI_Merge
on:
  push:
    branches: [ master, Beta, Alpha, Experimental ]
jobs:
  job1:
    # if: github.repository == 'OpenCPN/plugins'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update ocpn-plugins.xml
        run: ci/ga_merge.sh
        env:
          UPSTREAM: ${{ secrets.UPSTREAM }}
