name: CI_Pull
on:
  pull_request:
    branches: [ master, Alpha, Beta, Experimental ]
    types: [ opened, reopened, edited, review_requested, synchronize ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check PR files
        run: ci/ga_pull.sh
